### ISSUE TITLE
Kun fremtid vises

### ISSUE THREAD

**Issue by andreaskring** [magenta-aps/mora#5]
Development branch:
Efter sekvensen af operationer, som ses på vedhæftede skærmdump, vises kun "Fremtid":

![skaermbillede fra 2017-08-07 11-29-18](https://user-images.githubusercontent.com/12028976/29020888-d754ba1a-7b63-11e7-9fb5-fcaaea212d97.png)

**Comment by danchr** [comment]
Hvad giver ‘past’ i direkte output?

**Comment by andreaskring** [comment]
Mener du kaldet til `http://localhost:5000/o/59141156-ed0b-457c-9535-884447c5220b/org-unit/9b5221f0-1194-40c1-8a9f-44eaefa3e583/?validity=past&effective-date=&t=1502099563524`?
Det giver en fejl 404 og det samme gør det tilsvarende kald til "present".

Men det er muligvis min fejl, da jeg i det sidste skridt under testen satte en ny startdato for gyldigheden, som lå i fremtiden - og så giver det god mening, at der kun vises noget under "fremtid". Når man opdaterer siden, skriver frontend "Organisationen ikke fundet", hvilket er ok, men enheden kan stadig ses i træet til venstre

**Comment by danchr** [comment]
Ok, lukker.
